/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Control.ControlDias;
import Control.ConvertirMayusculas;
import Control.Validar;
import Datos.Conexion;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JTextField;

public class IU_GestionCaja extends javax.swing.JFrame {

    Validar v = new Validar();
    ControlDias dias = new ControlDias();

    public IU_GestionCaja() {
        initComponents();
        metodosIniciales();
        cargarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jdateoperacion = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cbxcliente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxoperacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtdetalle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfechahoy = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtimporte = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdiasrestantes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpromedio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemovimientos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnborrar = new javax.swing.JButton();
        txttotalmes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jdateoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 90, 140, 30));

        jLabel3.setText("Operación");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cbxcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 30));

        jLabel4.setText("Detalle");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/canilla.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 290, 330));

        cbxoperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxoperacionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, 30));

        jLabel5.setText("Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));
        jPanel1.add(txtdetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, 30));

        jLabel6.setText("Importe");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 30));

        txtfechahoy.setBorder(null);
        txtfechahoy.setFocusable(false);
        txtfechahoy.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtfechahoyCaretUpdate(evt);
            }
        });
        txtfechahoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechahoyActionPerformed(evt);
            }
        });
        jPanel1.add(txtfechahoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 160, 30));

        jLabel7.setText("Fecha Operacion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 120, 30));

        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, 30));

        txtimporte.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtimporteCaretUpdate(evt);
            }
        });
        txtimporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimporteActionPerformed(evt);
            }
        });
        txtimporte.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtimportePropertyChange(evt);
            }
        });
        jPanel1.add(txtimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 30));

        jLabel9.setText("Dias Laborales Restantes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 150, 30));

        jLabel10.setText("Ing/Mes");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 60, 30));

        txtdiasrestantes.setFocusable(false);
        txtdiasrestantes.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtdiasrestantesCaretUpdate(evt);
            }
        });
        txtdiasrestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiasrestantesActionPerformed(evt);
            }
        });
        jPanel1.add(txtdiasrestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 50, 30));

        jLabel11.setText("Promedio Dia");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 80, 30));

        txtpromedio.setFocusable(false);
        txtpromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpromedioActionPerformed(evt);
            }
        });
        jPanel1.add(txtpromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 50, 30));

        tablemovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablemovimientos.setFocusable(false);
        jScrollPane1.setViewportView(tablemovimientos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 500, 230));

        jLabel12.setFont(new java.awt.Font("FrankRuehl", 0, 18)); // NOI18N
        jLabel12.setText("Ultimos Movimientos");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        jLabel13.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel13.setText("CASHFLOW   -   v1.0");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 130, 40));

        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        txttotalmes.setFocusable(false);
        txttotalmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalmesActionPerformed(evt);
            }
        });
        jPanel1.add(txttotalmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtimporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimporteActionPerformed

    private void txtdiasrestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiasrestantesActionPerformed

    }//GEN-LAST:event_txtdiasrestantesActionPerformed

    private void txtpromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpromedioActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnborrarActionPerformed

    private void txtfechahoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechahoyActionPerformed

    }//GEN-LAST:event_txtfechahoyActionPerformed

    private void cbxoperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxoperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxoperacionActionPerformed

    private void txtimportePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtimportePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimportePropertyChange

    private void txtimporteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtimporteCaretUpdate

        txtimporte.setHorizontalAlignment(JTextField.RIGHT);// TODO add your handling code here:
    }//GEN-LAST:event_txtimporteCaretUpdate

    private void txttotalmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalmesActionPerformed

    private void txtdiasrestantesCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtdiasrestantesCaretUpdate

    }//GEN-LAST:event_txtdiasrestantesCaretUpdate

    private void txtfechahoyCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtfechahoyCaretUpdate

    }//GEN-LAST:event_txtfechahoyCaretUpdate

    public void cargarCombos() {
        Conexion con = CashFlow.hc;

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_GestionCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cbxcliente;
    private javax.swing.JComboBox<String> cbxoperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdateoperacion;
    private javax.swing.JTable tablemovimientos;
    private javax.swing.JTextField txtdetalle;
    private javax.swing.JTextField txtdiasrestantes;
    private javax.swing.JTextField txtfechahoy;
    private javax.swing.JTextField txtimporte;
    private javax.swing.JTextField txtpromedio;
    private javax.swing.JTextField txttotalmes;
    // End of variables declaration//GEN-END:variables

    private void metodosIniciales() {
        v.validarSoloLetras(txtdetalle);
        v.validarSoloNumeros(txtimporte);
        txtdetalle.setDocument(new ConvertirMayusculas());
        txtdiasrestantes.setEditable(false);
        txttotalmes.setEditable(false);
        txtpromedio.setEditable(false);
        txtdiasrestantes.setText("45");
        txtfechahoy.setHorizontalAlignment(JTextField.RIGHT);
        txtpromedio.setHorizontalAlignment(JTextField.RIGHT);
        txttotalmes.setHorizontalAlignment(JTextField.RIGHT);
        txtdiasrestantes.setHorizontalAlignment(JTextField.RIGHT);
        txtfechahoy.setText(dias.mostrarFecha());
        txtdiasrestantes.setText(dias.diasRestantes());
        txtpromedio.setText(dias.Promedio());
        txttotalmes.setText(dias.TotaldelMes());
    }
    
}
